name: Test

on: pull_request

env:
  NODE_VERSION: "12.16.3"

jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest

    timeout-minutes: 5

    services:
      db:
        image: postgres:13.4
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache Node npm
        uses: actions/cache@v2
        with:
          path: assets/node_modules
          key: ${{ runner.os }}-crit-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-crit-

      - name: Install Dependancies
        run: npm install

      - name: Create migrations
        run: npm run migrate:ci

      - name: Run tests
        run: npm test
